

spring:

  datasource:
#    primary:
      # 6.x版本的MySQL JDBC驱动类为com.mysql.cj.jdbc.Driver
      # 5.X版本的MySQL JDBC驱动类为com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mobileservice?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
#    shiro:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/mobileservice?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: 123456
  # Shiro


  thymeleaf:
           cache: false
           mode: LEGACYHTML5

  redis:
      host: 127.0.0.1
      port: 6379
      max-idle: 8
      min-idle: 0
      max-active: 8
      maxwait: -1
      timeout: 2000
      isRedisCache: 1  #是否使用redis缓存
#      nodes: 10.189.80.25:26379,10.189.80.26:263



mybatis:
  configLocation: classpath:MyBatisConf.xml
#       log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.sinosoft.mobileservice.bean.*
#  configuration:



  #################redis基础配置#################
  # spring.redis.database=5
  # spring.redis.host=19.29.80.50
  # spring.redis.password=admin.1231
  # spring.redis.port=7001
  # 连接超时时间 单位 ms（毫秒）
  # spring.redis.timeout=3000

  #################redis线程池设置#################
  # 连接池中的最大空闲连接，默认值也是8。
  # spring.redis.pool.max-idle=500
  #连接池中的最小空闲连接，默认值也是0。
  #spring.redis.pool.min-idle=50
  # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
  #spring.redis.pool.max-active=2000
  # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
  #spring.redis.pool.max-wait=1000

  #################redis哨兵设置#################
  # Redis服务器master的名字
  #spring.redis.sentinel.master=master8026
  # redis-sentinel的配置地址和端口
  #spring.redis.sentinel.nodes=10.189.80.25:26379,10.189.80.26:263








